name: Setup Environment
description: 设置基础环境（拉取代码、配置Python、安装依赖等）
runs:
  using: "composite"
  steps:
    - name: 验证时区设置
      shell: bash
      run: |
        echo "时区验证: $(date -u '+%Y-%m-%d %H:%M:%S' UTC) | $(TZ=Asia/Shanghai date '+%Y-%m-%d %H:%M:%S' CST)"
    
    - name: 拉取仓库代码
      uses: actions/checkout@v4
      with:
        ref: main
        fetch-depth: 0
        clean: true
        token: ${{ github.token }}
    
    - name: 配置Python环境
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
    
    - name: 安装依赖包
      shell: bash
      run: |
        echo "当前工作目录: $(pwd)"
        if [ -f "requirements.txt" ]; then
          echo "✅ requirements.txt 文件存在，开始安装依赖..."
          pip install -r requirements.txt
        else
          echo "❌ 错误: requirements.txt 文件不存在"
          ls -la
          exit 1
        fi
    
    - name: 创建数据目录
      shell: bash
      run: |
        mkdir -p data/{etf_daily,arbitrage,flags,logs,daily} && chmod -R 777 data/
