name: Execute Task
description: 执行任务并处理日志
inputs:
  task-name:
    description: "任务名称"
    required: true
  task-type:
    description: "任务类型"
    required: true
  webhook-secret:
    description: "Webhook密钥名称"
    required: true
  log-file:
    description: "日志文件名"
    required: true
  command:
    description: "执行命令"
    required: true
  skip-check:
    description: "跳过条件检查"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: 执行任务
      id: execute_task
      shell: bash
      env:
        WECOM_WEBHOOK: ${{ secrets.inputs.webhook-secret }}
        TZ: Asia/Shanghai
        TASK: ${{ inputs.task-type }}
      run: |
        BEIJING_TIME=$(date '+%Y%m%d_%H%M%S')
        LOG_FILE="${{ inputs.log-file }}_${BEIJING_TIME}.log"
        echo "正在执行: ${{ inputs.task-name }}"
        echo "日志文件: $LOG_FILE"
        ${{ inputs.command }} 2>&1 | tee "$LOG_FILE"
        
        # 记录任务状态
        if [ ${PIPESTATUS[0]} -eq 0 ]; then
          echo "task_status=success" >> $GITHUB_OUTPUT
        else
          echo "task_status=failed" >> $GITHUB_OUTPUT
        fi
        [ ${PIPESTATUS[0]} -eq 0 ] || exit 1
