name: Send Notification
description: 发送通知消息
inputs:
  status:
    description: "任务状态"
    required: true
  task-name:
    description: "任务名称"
    required: true
  webhook-secret:
    description: "Webhook密钥名称"
    required: true

runs:
  using: "composite"
  steps:
    - name: 发送通知
      if: env.WECOM_WEBHOOK
      shell: bash
      env:
        WECOM_WEBHOOK: ${{ secrets.inputs.webhook-secret }}
      run: |
        BEIJING_TIME=$(TZ=Asia/Shanghai date '+%Y-%m-%d %H:%M:%S')
        if [ "${{ inputs.status }}" = "success" ]; then
          MSG="✅ 【${{ inputs.task-name }}】执行成功"
        else
          MSG="❌ 【${{ inputs.task-name }}】执行失败"
        fi
        curl -s -X POST "$WECOM_WEBHOOK" -H "Content-Type: application/json" \
          -d "{\"msgtype\": \"text\", \"text\": {\"content\": \"$MSG\\n北京时间: ${BEIJING_TIME}\"}}"
