name: 定时任务
on:
  schedule:
    - cron: '0 10 * * 1-5'   # UTC 10:00 = 北京时间 18:00 (ETF日线爬取)
    - cron: '*/5 2-7 * * 1-5' # UTC 02:00-07:00 = 北京时间 10:00-15:00 (ETF套利计算)
    - cron: '30 5 * * 1-5'    # UTC 05:30 = 北京时间 13:30 (ETF仓位策略)
    - cron: '0 1 * * 0'       # UTC 01:00 = 北京时间 09:00 (ETF列表更新)
    - cron: '0 8 * * *'       # UTC 08:00 = 北京时间 16:00 (指数Yes/No)
    - cron: '30 0 * * 1-5'    # UTC 0:30 = 北京时间 8:30 (个股趋势策略)
    - cron: '*/10 12-22 * * *'    # UTC 11:00 = 北京时间 20:00-06:00 (股票日线爬取)
  workflow_dispatch:
    inputs:
      task:
        description: '任务类型'
        required: true
        type: choice
        options:
          - 'update_etf_list'
          - 'crawl_etf_daily'
          - 'calculate_arbitrage'
          - 'calculate_position'
          - 'etf_yesno'
          - 'stock_fourty'
          - 'stock_crawler'
jobs:
  # ========================
  # 定时任务 - 每个任务都有独立Job
  # ========================
  # ETF日线数据爬取（定时）
  crawl-etf-daily-schedule:
    name: ETF日线爬取（定时）
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'schedule' && github.event.schedule == '0 10 * * 1-5' }}
    permissions:
      contents: write
    steps:
      - name: 验证时区设置
        run: |
          echo "时区验证: $(date -u '+%Y-%m-%d %H:%M:%S' UTC) | $(TZ=Asia/Shanghai date '+%Y-%m-%d %H:%M:%S' CST)"
      
      - name: 拉取仓库代码
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
          clean: true
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: 配置Python环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      
      - name: 安装依赖包
        run: |
          echo "当前工作目录: $(pwd)"
          if [ -f "requirements.txt" ]; then
            echo "✅ requirements.txt 文件存在，开始安装依赖..."
            pip install -r requirements.txt
          else
            echo "❌ 错误: requirements.txt 文件不存在"
            ls -la
            exit 1
          fi
      
      - name: 创建数据目录
        run: |
          mkdir -p data/{etf_daily,flags,logs} && chmod -R 777 data/
      
      - name: 检查交易日
        id: check_trading_day
        run: |
          IS_TRADING_DAY=$(TZ=Asia/Shanghai date '+%u' | awk '$1 <= 5 {print "true"}')
          echo "IS_TRADING_DAY=${IS_TRADING_DAY:-false}" >> $GITHUB_OUTPUT
          echo "交易日检查: ${IS_TRADING_DAY:-false}"
      
      - name: 跳过非交易日
        if: ${{ steps.check_trading_day.outputs.IS_TRADING_DAY == 'false' }}
        run: |
          echo "skip_execution=true" >> $GITHUB_ENV
      
      - name: 执行ETF日线数据爬取（定时）
        id: execute_task
        if: ${{ env.skip_execution != 'true' }}
        env:
          WECOM_WEBHOOK: ${{ secrets.WECOM_WEBHOOK }}
          TZ: Asia/Shanghai
          TASK: 'crawl_etf_daily'
        run: |
          BEIJING_TIME=$(date '+%Y%m%d_%H%M%S')
          LOG_FILE="data/logs/crawl_etf_daily_${BEIJING_TIME}.log"
          echo "正在执行: ETF日线数据爬取（定时）"
          echo "日志文件: $LOG_FILE"
          python main.py 2>&1 | tee "$LOG_FILE"
          
          # 记录任务状态
          if [ ${PIPESTATUS[0]} -eq 0 ]; then
            echo "task_status=success" >> $GITHUB_OUTPUT
          else
            echo "task_status=failed" >> $GITHUB_OUTPUT
          fi
          [ ${PIPESTATUS[0]} -eq 0 ] || exit 1
      
      - name: 发送完成通知
        if: ${{ steps.execute_task.outputs.task_status == 'success' && env.WECOM_WEBHOOK }}
        run: |
          BEIJING_TIME=$(TZ=Asia/Shanghai date '+%Y-%m-%d %H:%M:%S')
          # 检查是否有新提交
          HAS_NEW_COMMITS=$(git log -1 --since="1 hour ago" -- data/etf_daily/ | wc -l)
          
          if [ "$HAS_NEW_COMMITS" -gt 0 ]; then
            MSG="✅ 【ETF日线数据爬取（定时）】执行成功并已提交"
          else
            MSG="⚠️ 【ETF日线数据爬取（定时）】执行成功但无新提交（可能数据无变化）"
          fi
          
          curl -s -X POST "$WECOM_WEBHOOK" -H "Content-Type: application/json" \
            -d "{\"msgtype\": \"text\", \"text\": {\"content\": \"$MSG\\n北京时间: ${BEIJING_TIME}\"}}"
      
      - name: 发送失败通知
        if: ${{ failure() && env.WECOM_WEBHOOK }}
        run: |
          BEIJING_TIME=$(TZ=Asia/Shanghai date '+%Y-%m-%d %H:%M:%S')
          curl -s -X POST "$WECOM_WEBHOOK" -H "Content-Type: application/json" \
            -d "{\"msgtype\": \"text\", \"text\": {\"content\": \"❌ 【ETF日线数据爬取（定时）】执行失败\\n北京时间: ${BEIJING_TIME}\"}}"

  # ETF套利计算（定时）
  calculate-arbitrage-schedule:
    name: ETF套利计算（定时）
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'schedule' && github.event.schedule == '*/5 2-7 * * 1-5' }}
    permissions:
      contents: write
    steps:
      - name: 验证时区设置
        run: |
          echo "时区验证: $(date -u '+%Y-%m-%d %H:%M:%S' UTC) | $(TZ=Asia/Shanghai date '+%Y-%m-%d %H:%M:%S' CST)"
      
      - name: 拉取仓库代码
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
          clean: true
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: 配置Python环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      
      - name: 安装依赖包
        run: |
          echo "当前工作目录: $(pwd)"
          if [ -f "requirements.txt" ]; then
            echo "✅ requirements.txt 文件存在，开始安装依赖..."
            pip install -r requirements.txt
          else
            echo "❌ 错误: requirements.txt 文件不存在"
            ls -la
            exit 1
          fi
      
      - name: 创建数据目录
        run: |
          mkdir -p data/{arbitrage,flags,logs} && chmod -R 777 data/
      
      - name: 执行ETF套利计算（定时）
        id: execute_task
        env:
          WECOM_WEBHOOK: ${{ secrets.WECOM_WEBHOOK }}
          TZ: Asia/Shanghai
          TASK: 'calculate_arbitrage'
        run: |
          BEIJING_TIME=$(date '+%Y%m%d_%H%M%S')
          LOG_FILE="data/logs/calculate_arbitrage_${BEIJING_TIME}.log"
          echo "正在执行: ETF套利计算（定时）"
          echo "日志文件: $LOG_FILE"
          python main.py 2>&1 | tee "$LOG_FILE"
          
          # 记录任务状态
          if [ ${PIPESTATUS[0]} -eq 0 ]; then
            echo "task_status=success" >> $GITHUB_OUTPUT
          else
            echo "task_status=failed" >> $GITHUB_OUTPUT
          fi
          [ ${PIPESTATUS[0]} -eq 0 ] || exit 1
      
      - name: 提交数据变更
        if: ${{ steps.execute_task.outputs.task_status == 'success' }}
        run: |
          git config user.name "GitHub Actions" && git config user.email "actions@github.com"
          
          # 只添加套利相关文件
          git add data/arbitrage/ data/flags/{discount,premium}_status.json
          
          # 检查暂存区是否有变化（关键修复）
          if [ -n "$(git diff --cached --name-only)" ]; then
            echo "检测到ETF套利数据变化，准备提交..."
            git commit -m "自动更新套利数据 [定时]" && git push origin main
          fi

      - name: 发送完成通知
        if: ${{ steps.execute_task.outputs.task_status == 'success' && env.WECOM_WEBHOOK }}
        run: |
          BEIJING_TIME=$(TZ=Asia/Shanghai date '+%Y-%m-%d %H:%M:%S')
          # 检查是否有新提交
          HAS_NEW_COMMITS=$(git log -1 --since="1 hour ago" -- data/arbitrage/ | wc -l)
          
          if [ "$HAS_NEW_COMMITS" -gt 0 ]; then
            MSG="✅ 【ETF套利计算（定时）】执行成功并已提交"
          else
            MSG="ℹ️ 【ETF套利计算（定时）】执行成功但无新提交（可能数据无变化）"
          fi
          
          curl -s -X POST "$WECOM_WEBHOOK" -H "Content-Type: application/json" \
            -d "{\"msgtype\": \"text\", \"text\": {\"content\": \"$MSG\\n北京时间: ${BEIJING_TIME}\"}}"
      
      - name: 发送失败通知
        if: ${{ failure() && env.WECOM_WEBHOOK }}
        run: |
          BEIJING_TIME=$(TZ=Asia/Shanghai date '+%Y-%m-%d %H:%M:%S')
          curl -s -X POST "$WECOM_WEBHOOK" -H "Content-Type: application/json" \
            -d "{\"msgtype\": \"text\", \"text\": {\"content\": \"❌ 【ETF套利计算（定时）】执行失败\\n北京时间: ${BEIJING_TIME}\"}}"

  # ETF仓位策略计算（定时）
  calculate-position-schedule:
    name: ETF仓位策略计算（定时）
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'schedule' && github.event.schedule == '30 5 * * 1-5' }}
    permissions:
      contents: write
    steps:
      - name: 验证时区设置
        run: |
          echo "时区验证: $(date -u '+%Y-%m-%d %H:%M:%S' UTC) | $(TZ=Asia/Shanghai date '+%Y-%m-%d %H:%M:%S' CST)"
      
      - name: 拉取仓库代码
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
          clean: true
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: 配置Python环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      
      - name: 安装依赖包
        run: |
          echo "当前工作目录: $(pwd)"
          if [ -f "requirements.txt" ]; then
            echo "✅ requirements.txt 文件存在，开始安装依赖..."
            pip install -r requirements.txt
          else
            echo "❌ 错误: requirements.txt 文件不存在"
            ls -la
            exit 1
          fi
      
      - name: 创建数据目录
        run: |
          mkdir -p data/{flags,logs} && chmod -R 777 data/
      
      - name: 检查推送标志
        id: check_flags
        run: |
          BEIJING_DATE=$(TZ=Asia/Shanghai date '+%Y-%m-%d')
          echo "position_pushed=$( [ -f "data/flags/position_pushed_${BEIJING_DATE}.txt" ] && echo true || echo false )" >> $GITHUB_OUTPUT
      
      - name: 跳过已推送任务
        if: ${{ steps.check_flags.outputs.position_pushed == 'true' }}
        run: |
          echo "skip_execution=true" >> $GITHUB_ENV
      
      - name: 执行ETF仓位策略计算（定时）
        id: execute_task
        if: ${{ env.skip_execution != 'true' }}
        env:
          WECOM_WEBHOOK: ${{ secrets.WECOM_WEBHOOK }}
          TZ: Asia/Shanghai
          TASK: 'calculate_position'
        run: |
          BEIJING_TIME=$(date '+%Y%m%d_%H%M%S')
          LOG_FILE="data/logs/calculate_position_${BEIJING_TIME}.log"
          echo "正在执行: ETF仓位策略计算（定时）"
          echo "日志文件: $LOG_FILE"
          python main.py 2>&1 | tee "$LOG_FILE"
          
          # 记录任务状态
          if [ ${PIPESTATUS[0]} -eq 0 ]; then
            echo "task_status=success" >> $GITHUB_OUTPUT
          else
            echo "task_status=failed" >> $GITHUB_OUTPUT
          fi
          [ ${PIPESTATUS[0]} -eq 0 ] || exit 1
      
      - name: 创建ETF仓位推送标志
        if: ${{ env.skip_execution != 'true' && steps.execute_task.outputs.task_status == 'success' }}
        run: |
          BEIJING_DATE=$(TZ=Asia/Shanghai date '+%Y-%m-%d')
          echo "执行完成" > "data/flags/position_pushed_${BEIJING_DATE}.txt"
          git config user.name "GitHub Actions" && git config user.email "actions@github.com"
          
          git add "data/flags/position_pushed_${BEIJING_DATE}.txt"
          # 检查暂存区是否有变化（关键修复）
          if [ -n "$(git diff --cached --name-only)" ]; then
            git commit -m "ETF仓位策略已推送标志 [定时]" && git push origin main
          fi
      
      - name: 发送完成通知
        if: ${{ steps.execute_task.outputs.task_status == 'success' && env.WECOM_WEBHOOK }}
        run: |
          BEIJING_TIME=$(TZ=Asia/Shanghai date '+%Y-%m-%d %H:%M:%S')
          # 检查是否有新提交
          HAS_NEW_COMMITS=$(git log -1 --since="1 hour ago" -- data/flags/position_pushed_${BEIJING_DATE}.txt | wc -l)
          
          if [ "$HAS_NEW_COMMITS" -gt 0 ]; then
            MSG="✅ 【ETF仓位策略计算（定时）】执行成功并提交"
          else
            MSG="ℹ️ 【ETF仓位策略计算（定时）】执行成功但无新提交（可能数据无变化）"
          fi
          
          curl -s -X POST "$WECOM_WEBHOOK" -H "Content-Type: application/json" \
            -d "{\"msgtype\": \"text\", \"text\": {\"content\": \"$MSG\\n北京时间: ${BEIJING_TIME}\"}}"
      
      - name: 发送失败通知
        if: ${{ failure() && env.WECOM_WEBHOOK }}
        run: |
          BEIJING_TIME=$(TZ=Asia/Shanghai date '+%Y-%m-%d %H:%M:%S')
          curl -s -X POST "$WECOM_WEBHOOK" -H "Content-Type: application/json" \
            -d "{\"msgtype\": \"text\", \"text\": {\"content\": \"❌ 【ETF仓位策略计算（定时）】执行失败\\n北京时间: ${BEIJING_TIME}\"}}"

  # ETF列表更新（定时）
  update-etf-list-schedule:
    name: ETF列表更新（定时）
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'schedule' && github.event.schedule == '0 1 * * 0' }}
    permissions:
      contents: write
    steps:
      - name: 验证时区设置
        run: |
          echo "时区验证: $(date -u '+%Y-%m-%d %H:%M:%S' UTC) | $(TZ=Asia/Shanghai date '+%Y-%m-%d %H:%M:%S' CST)"
      
      - name: 拉取仓库代码
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
          clean: true
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: 配置Python环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      
      - name: 安装依赖包
        run: |
          echo "当前工作目录: $(pwd)"
          if [ -f "requirements.txt" ]; then
            echo "✅ requirements.txt 文件存在，开始安装依赖..."
            pip install -r requirements.txt
          else
            echo "❌ 错误: requirements.txt 文件不存在"
            ls -la
            exit 1
          fi
      
      - name: 创建数据目录
        run: |
          mkdir -p data/{flags,logs} && chmod -R 777 data/
      
      - name: 执行ETF列表更新（定时）
        id: execute_task
        env:
          WECOM_WEBHOOK: ${{ secrets.WECOM_WEBHOOK }}
          TZ: Asia/Shanghai
          TASK: 'update_etf_list'
        run: |
          BEIJING_TIME=$(date '+%Y%m%d_%H%M%S')
          LOG_FILE="data/logs/update_etf_list_${BEIJING_TIME}.log"
          echo "正在执行: ETF列表更新（定时）"
          echo "日志文件: $LOG_FILE"
          python main.py 2>&1 | tee "$LOG_FILE"
          
          # 记录任务状态
          if [ ${PIPESTATUS[0]} -eq 0 ]; then
            echo "task_status=success" >> $GITHUB_OUTPUT
          else
            echo "task_status=failed" >> $GITHUB_OUTPUT
          fi
          [ ${PIPESTATUS[0]} -eq 0 ] || exit 1
      
      - name: 提交ETF列表数据变更
        if: ${{ steps.execute_task.outputs.task_status == 'success' }}
        run: |
          git config user.name "GitHub Actions" && git config user.email "actions@github.com"
          git add data/all_etfs.csv
          # 检查暂存区是否有变化（关键修复）
          if [ -n "$(git diff --cached --name-only)" ]; then
            git commit -m "自动更新ETF列表 [定时]" && git push origin main
          fi
      
      - name: 发送完成通知
        if: ${{ steps.execute_task.outputs.task_status == 'success' && env.WECOM_WEBHOOK }}
        run: |
          BEIJING_TIME=$(TZ=Asia/Shanghai date '+%Y-%m-%d %H:%M:%S')
          # 检查是否有新提交
          HAS_NEW_COMMITS=$(git log -1 --since="1 hour ago" -- data/all_etfs.csv | wc -l)
          
          if [ "$HAS_NEW_COMMITS" -gt 0 ]; then
            MSG="✅ 【ETF列表更新（定时）】执行成功并提交"
          else
            MSG="ℹ️ 【ETF列表更新（定时）】执行成功但无新提交（可能数据无变化）"
          fi
          
          curl -s -X POST "$WECOM_WEBHOOK" -H "Content-Type: application/json" \
            -d "{\"msgtype\": \"text\", \"text\": {\"content\": \"$MSG\\n北京时间: ${BEIJING_TIME}\"}}"
      
      - name: 发送失败通知
        if: ${{ failure() && env.WECOM_WEBHOOK }}
        run: |
          BEIJING_TIME=$(TZ=Asia/Shanghai date '+%Y-%m-%d %H:%M:%S')
          curl -s -X POST "$WECOM_WEBHOOK" -H "Content-Type: application/json" \
            -d "{\"msgtype\": \"text\", \"text\": {\"content\": \"❌ 【ETF列表更新（定时）】执行失败\\n北京时间: ${BEIJING_TIME}\"}}"

  # 指数Yes/No 策略（定时）
  etf-yesno-schedule:
    name: 指数Yes/No 策略（定时）
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'schedule' && github.event.schedule == '0 8 * * *' }}
    permissions:
      contents: write
    steps:
      - name: 验证时区设置
        run: |
          echo "时区验证: $(date -u '+%Y-%m-%d %H:%M:%S' UTC) | $(TZ=Asia/Shanghai date '+%Y-%m-%d %H:%M:%S' CST)"
      
      - name: 拉取仓库代码
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
          clean: true
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: 配置Python环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      
      - name: 安装依赖包
        run: |
          echo "当前工作目录: $(pwd)"
          if [ -f "requirements.txt" ]; then
            echo "✅ requirements.txt 文件存在，开始安装依赖..."
            pip install -r requirements.txt
          else
            echo "❌ 错误: requirements.txt 文件不存在"
            ls -la
            exit 1
          fi
      
      - name: 创建数据目录
        run: |
          mkdir -p data/{flags,logs} && chmod -R 777 data/
      
      - name: 执行指数Yes/No策略（定时）
        id: execute_task
        env:
          WECOM_WEBHOOK: ${{ secrets.WECOM_ETFYESNO }}
          TZ: Asia/Shanghai
          TASK: 'etf_yesno'
        run: |
          BEIJING_TIME=$(date '+%Y%m%d_%H%M%S')
          LOG_FILE="data/logs/etf_yesno_${BEIJING_TIME}.log"
          echo "正在执行: 指数Yes/No 策略（定时）"
          echo "日志文件: $LOG_FILE"
          python main.py 2>&1 | tee "$LOG_FILE"
          
          # 记录任务状态
          if [ ${PIPESTATUS[0]} -eq 0 ]; then
            echo "task_status=success" >> $GITHUB_OUTPUT
          else
            echo "task_status=failed" >> $GITHUB_OUTPUT
          fi
          [ ${PIPESTATUS[0]} -eq 0 ] || exit 1
      
      - name: 发送完成通知
        if: ${{ steps.execute_task.outputs.task_status == 'success' && env.WECOM_WEBHOOK }}
        run: |
          BEIJING_TIME=$(TZ=Asia/Shanghai date '+%Y-%m-%d %H:%M:%S')
          # 检查是否有新提交
          HAS_NEW_COMMITS=$(git log -1 --since="1 hour ago" -- data/flags/yesno_*.txt | wc -l)
          
          if [ "$HAS_NEW_COMMITS" -gt 0 ]; then
            MSG="✅ 【指数Yes/No策略（定时）】执行成功并提交"
          else
            MSG="ℹ️ 【指数Yes/No策略（定时）】执行成功但无新提交（可能数据无变化）"
          fi
          
          curl -s -X POST "$WECOM_WEBHOOK" -H "Content-Type: application/json" \
            -d "{\"msgtype\": \"text\", \"text\": {\"content\": \"$MSG\\n北京时间: ${BEIJING_TIME}\"}}"
      
      - name: 发送失败通知
        if: ${{ failure() && env.WECOM_WEBHOOK }}
        run: |
          BEIJING_TIME=$(TZ=Asia/Shanghai date '+%Y-%m-%d %H:%M:%S')
          curl -s -X POST "$WECOM_WEBHOOK" -H "Content-Type: application/json" \
            -d "{\"msgtype\": \"text\", \"text\": {\"content\": \"❌ 【指数Yes/No策略（定时）】执行失败\\n北京时间: ${BEIJING_TIME}\"}}"

  # 个股趋势策略（定时）
  stock-fourty-schedule:
    name: 个股趋势策略 (TickTen) - 定时
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'schedule' && github.event.schedule == '30 0 * * 1-5' }}
    permissions:
      contents: write
    steps:
      - name: 验证时区设置
        run: |
          echo "时区验证: $(date -u '+%Y-%m-%d %H:%M:%S' UTC) | $(TZ=Asia/Shanghai date '+%Y-%m-%d %H:%M:%S' CST)"
      
      - name: 拉取仓库代码
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
          clean: true
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: 配置Python环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      
      - name: 安装依赖包
        run: |
          echo "当前工作目录: $(pwd)"
          if [ -f "requirements.txt" ]; then
            echo "✅ requirements.txt 文件存在，开始安装依赖..."
            pip install -r requirements.txt
          else
            echo "❌ 错误: requirements.txt 文件不存在"
