name: 清理数据文件任务-akshare信息
on:
  workflow_dispatch:
    inputs:
      task:
        description: '任务类型'
        required: true
        type: choice
        options:
          - 'show_akshare_info'
          - 'clean_stock_daily_data'
          - 'clean_daily_data'
          - 'clean_arbitrage_data'
          - 'clean_trade_records'
          - 'clean_numeric_csv'
      interface_name:
        description: 'AkShare接口名称（可选）'
        required: false
        type: string
        default: ''
jobs:
  # ========================
  # 显示AkShare信息
  # ========================
  show-akshare-info:
    name: 显示AkShare信息
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.task == 'show_akshare_info'
    permissions:
      contents: write
    steps:
      - name: 拉取仓库代码
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
          clean: true
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: 设置环境
        uses: ./.github/actions/setup_environment
      
      - name: 获取AkShare信息
        run: |
          INTERFACE_NAME="${{ github.event.inputs.interface_name }}"
          echo "正在获取AkShare信息: ${INTERFACE_NAME:-默认接口}"
          
          # 执行获取信息
          python data_crawler/get_akshare_info.py ${INTERFACE_NAME:+$INTERFACE_NAME}
      
      - name: 发送完成通知
        if: success()
        run: |
          BEIJING_TIME=$(TZ=Asia/Shanghai date '+%Y-%m-%d %H:%M:%S')
          MSG="✅ 【AkShare信息】获取成功"
          [ -n "${{ github.event.inputs.interface_name }}" ] && MSG="✅ 【AkShare信息】已查询接口: ${{ github.event.inputs.interface_name }}"
          curl -s -X POST "$WECOM_WEBHOOK" -H "Content-Type: application/json" \
            -d "{\"msgtype\": \"text\", \"text\": {\"content\": \"$MSG\\n北京时间: ${BEIJING_TIME}\"}}"
      
      - name: 发送失败通知
        if: failure()
        run: |
          BEIJING_TIME=$(TZ=Asia/Shanghai date '+%Y-%m-%d %H:%M:%S')
          curl -s -X POST "$WECOM_WEBHOOK" -H "Content-Type: application/json" \
            -d "{\"msgtype\": \"text\", \"text\": {\"content\": \"❌ 【AkShare信息】执行失败\\n北京时间: ${BEIJING_TIME}\"}}"

  # ========================
  # 清理任务 - 每个任务都有独立Job
  # ========================
  # 手动清理ETF日线数据
  manual-clean-daily-data:
    name: 手动清理ETF日线数据
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.task == 'clean_daily_data'
    permissions:
      contents: write
    steps:
      - name: 拉取仓库代码
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
          clean: true
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: 设置环境
        uses: ./.github/actions/setup_environment
      
      - name: 清理ETF日线数据
        run: |
          echo "删除 data/etf_daily/*.csv"
          rm -rf data/etf_daily/*.csv
      
      - name: 检查文件状态（诊断）
        if: success()
        run: |
          echo "清理后 data/etf_daily/ 目录状态:"
          ls -la data/etf_daily/ 2>/dev/null || echo "目录不存在或为空"
      
      - name: 发送清理通知
        if: success()
        run: |
          BEIJING_TIME=$(TZ=Asia/Shanghai date '+%Y-%m-%d %H:%M:%S')
          curl -s -X POST "$WECOM_WEBHOOK" -H "Content-Type: application/json" \
            -d "{\"msgtype\": \"text\", \"text\": {\"content\": \"✅ 【手動清理】ETF日线数据文件已清理完成\\n北京时间: ${BEIJING_TIME}\"}}"
      
      - name: 发送清理失败通知
        if: failure()
        run: |
          BEIJING_TIME=$(TZ=Asia/Shanghai date '+%Y-%m-%d %H:%M:%S')
          curl -s -X POST "$WECOM_WEBHOOK" -H "Content-Type: application/json" \
            -d "{\"msgtype\": \"text\", \"text\": {\"content\": \"❌ 【手動清理】ETF日线数据文件清理失败\\n北京时间: ${BEIJING_TIME}\"}}"

  # 新增：手動清理股票日线数据
  manual-clean-stock-daily-data:
    name: 手动清理股票日线数据
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.task == 'clean_stock_daily_data'
    permissions:
      contents: write
    steps:
      - name: 拉取仓库代码
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
          clean: true
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: 设置环境
        uses: ./.github/actions/setup_environment
      
      - name: 清理股票日线数据
        run: |
          echo "删除 data/daily/*.csv"
          rm -rf data/daily/*.csv
      
      - name: 检查文件状态（诊断）
        if: success()
        run: |
          echo "清理后 data/daily/ 目录状态:"
          ls -la data/daily/ 2>/dev/null || echo "目录不存在或为空"
      
      - name: 发送清理通知
        if: success()
        run: |
          BEIJING_TIME=$(TZ=Asia/Shanghai date '+%Y-%m-%d %H:%M:%S')
          curl -s -X POST "$WECOM_WEBHOOK" -H "Content-Type: application/json" \
            -d "{\"msgtype\": \"text\", \"text\": {\"content\": \"✅ 【手動清理】股票日线数据文件已清理完成\\n北京时间: ${BEIJING_TIME}\"}}"
      
      - name: 发送清理失败通知
        if: failure()
        run: |
          BEIJING_TIME=$(TZ=Asia/Shanghai date '+%Y-%m-%d %H:%M:%S')
          curl -s -X POST "$WECOM_WEBHOOK" -H "Content-Type: application/json" \
            -d "{\"msgtype\": \"text\", \"text\": {\"content\": \"❌ 【手動清理】股票日线数据文件清理失败\\n北京时间: ${BEIJING_TIME}\"}}"

  # 手动清理ETF套利数据
  manual-clean-arbitrage-data:
    name: 手动清理ETF套利数据
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.task == 'clean_arbitrage_data'
    permissions:
      contents: write
    steps:
      - name: 拉取仓库代码
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
          clean: true
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: 设置环境
        uses: ./.github/actions/setup_environment
      
      - name: 清理ETF套利数据
        run: |
          echo "删除 data/arbitrage/*.csv"
          rm -rf data/arbitrage/*.csv
      
      - name: 检查文件状态（诊断）
        if: success()
        run: |
          echo "清理后 data/arbitrage/ 目录状态:"
          ls -la data/arbitrage/ 2>/dev/null || echo "目录不存在或为空"
      
      - name: 发送清理通知
        if: success()
        run: |
          BEIJING_TIME=$(TZ=Asia/Shanghai date '+%Y-%m-%d %H:%M:%S')
          curl -s -X POST "$WECOM_WEBHOOK" -H "Content-Type: application/json" \
            -d "{\"msgtype\": \"text\", \"text\": {\"content\": \"✅ 【手動清理】ETF套利数据文件已清理完成\\n北京时间: ${BEIJING_TIME}\"}}"
      
      - name: 发送清理失败通知
        if: failure()
        run: |
          BEIJING_TIME=$(TZ=Asia/Shanghai date '+%Y-%m-%d %H:%M:%S')
          curl -s -X POST "$WECOM_WEBHOOK" -H "Content-Type: application/json" \
            -d "{\"msgtype\": \"text\", \"text\": {\"content\": \"❌ 【手動清理】ETF套利数据文件清理失败\\n北京时间: ${BEIJING_TIME}\"}}"

  # 手动清理ETF交易记录
  manual-clean-trade-records:
    name: 手动清理ETF交易记录
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.task == 'clean_trade_records'
    permissions:
      contents: write
    steps:
      - name: 拉取仓库代码
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
          clean: true
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: 设置环境
        uses: ./.github/actions/setup_environment
      
      - name: 清理ETF交易记录
        run: |
          echo "删除 data/trade_records.csv"
          rm -f data/trade_records.csv
      
      - name: 检查文件状态（诊断）
        if: success()
        run: |
          echo "清理后 data/trade_records.csv 状态:"
          ls -la data/trade_records.csv 2>/dev/null || echo "文件不存在"
      
      - name: 发送清理通知
        if: success()
        run: |
          BEIJING_TIME=$(TZ=Asia/Shanghai date '+%Y-%m-%d %H:%M:%S')
          curl -s -X POST "$WECOM_WEBHOOK" -H "Content-Type: application/json" \
            -d "{\"msgtype\": \"text\", \"text\": {\"content\": \"✅ 【手動清理】ETF交易记录文件已清理完成\\n北京时间: ${BEIJING_TIME}\"}}"
      
      - name: 发送清理失败通知
        if: failure()
        run: |
          BEIJING_TIME=$(TZ=Asia/Shanghai date '+%Y-%m-%d %H:%M:%S')
          curl -s -X POST "$WECOM_WEBHOOK" -H "Content-Type: application/json" \
            -d "{\"msgtype\": \"text\", \"text\": {\"content\": \"❌ 【手動清理】ETF交易记录文件清理失败\\n北京时间: ${BEIJING_TIME}\"}}"

  # 手动清理纯数字CSV
  manual-clean-numeric-csv:
    name: 手动清理纯数字CSV
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.task == 'clean_numeric_csv'
    permissions:
      contents: write
    steps:
      - name: 拉取仓库代码
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
          clean: true
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: 设置环境
        uses: ./.github/actions/setup_environment
      
      - name: 清理纯数字CSV
        run: |
          echo "删除纯数字CSV文件"
          find data/ -type f -name '[0-9]*.csv' -delete
      
      - name: 检查文件状态（诊断）
        if: success()
        run: |
          echo "清理后纯数字CSV文件状态:"
          find data/ -type f -name '[0-9]*.csv' || echo "无纯数字CSV文件"
      
      - name: 发送清理通知
        if: success()
        run: |
          BEIJING_TIME=$(TZ=Asia/Shanghai date '+%Y-%m-%d %H:%M:%S')
          curl -s -X POST "$WECOM_WEBHOOK" -H "Content-Type: application/json" \
            -d "{\"msgtype\": \"text\", \"text\": {\"content\": \"✅ 【手動清理】纯数字CSV文件已清理完成\\n北京时间: ${BEIJING_TIME}\"}}"
      
      - name: 发送清理失败通知
        if: failure()
        run: |
          BEIJING_TIME=$(TZ=Asia/Shanghai date '+%Y-%m-%d %H:%M:%S')
          curl -s -X POST "$WECOM_WEBHOOK" -H "Content-Type: application/json" \
            -d "{\"msgtype\": \"text\", \"text\": {\"content\": \"❌ 【手動清理】纯数字CSV文件清理失败\\n北京时间: ${BEIJING_TIME}\"}}"
